### ISSUE TITLE
Wrong word in sql_questions_classification ("account" instead of "houses")?

### ISSUE THREAD

**Issue by n1oftheabove** [ironhack-edu/data_mid_bootcamp_project_classification#1]
Typo at `8. ` in [`https://github.com/ironhack-edu/data_mid_bootcamp_project_classification/blob/master/sql_questions_classification.md`](https://github.com/ironhack-edu/data_mid_bootcamp_project_classification/blob/master/sql_questions_classification.md)

_8. Arrange the data in a decreasing order by the average_balance **of the house**. Return only the customer_number of the top 10 customers with the highest average_balances in your data_

should probably be **account** or sth. like that

**Comment by ironhack-edu** [comment]
@haggarw3 can you please check this one?

**Comment by haggarw3** [comment]
In this query we only need the "Customer Number". The column "Bank Account Open" corresponds to the number of bank accounts open by the customer. In this query, you would only need to sort the data and return the customer numbers. 
Hope this helps!
